### ISSUE TITLE
P3: New major version documentation Epic

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#2116]
This issue keeps track of all issues related to the promotion to GA of a handful of preview features, some of which came with breaking changes.

- [x] https://github.com/prisma/docs/issues/2115
- [x] https://github.com/prisma/docs/issues/2121
- [x] https://github.com/prisma/docs/issues/2122
- [x] https://github.com/prisma/docs/issues/1957
- [x] https://github.com/prisma/docs/issues/2135
- [x] https://github.com/prisma/docs/issues/2157
- [x] https://github.com/prisma/docs/issues/1895 - To be created by team and with Pr to be reviewed
- [x] #2168
- [x] https://github.com/prisma/docs/issues/2123
- [x] https://github.com/prisma/docs/issues/2150
- [x] Graduating `orderByRelations` to GA
- [x] Graduating `selectRelationCount` to GA
- [x] Graduating `orderByAggregateGroup` to GA
- [x] Graduating `filterJson` to GA
- [x] Graduating `referentialActions` to GA
